name: Build and Deploy to S3

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build for Linux (${{ matrix.arch }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, aarch64]
        ghc: ['9.4.8'] # You can adjust GHC versions as needed

    steps:
    - uses: actions/checkout@v4

    - name: Set up Haskell environment
      uses: haskell-actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: latest

    - name: Configure Cabal
      run: cabal update

    - name: Build project
      run: cabal build -j$(nproc)

    - name: Install project
      run: cabal install --installdir=./bin

    - name: Upload executable to S3
      uses: actions/upload-artifact@v4 # Using artifact for cross-job transfer
      with:
        name: linux-executable-${{ matrix.arch }}
        path: bin/calc

  deploy:
    name: Deploy to S3
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write # For OIDC based authentication

    steps:
    - name: Download executable (x86_64)
      uses: actions/download-artifact@v4
      with:
        name: linux-executable-x86_64
        path: x86_64-build/

    - name: Download executable (arm64)
      uses: actions/download-artifact@v4
      with:
        name: linux-executable-aarch64
        path: aarch64-build/

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ca-central-1

    - name: Upload to S3
      run: |
        aws s3 cp x86_64-build/* s3://rcbilson-dist/Linux/x86_64/ --acl public-read
        aws s3 cp aarch64-build/* s3://rcbilson-dist/Linux/aarch64/ --acl public-read
