name: Build and Deploy to S3

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-24.04', 'ubuntu-24.04-arm']
        ghc: ['9.4.8'] # You can adjust GHC versions as needed
    name: Build for Linux (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Haskell environment
      uses: haskell-actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: latest

    - name: Configure Cabal
      run: cabal update

    - name: Test project
      run: cabal test -j$(nproc)

    - name: Build project
      run: cabal build -j$(nproc)

    - name: Install project
      run: |
        cabal install --installdir=./bin
        strip bin/calc

    - name: Upload executable to S3
      uses: actions/upload-artifact@v4 # Using artifact for cross-job transfer
      with:
        name: linux-executable-${{ matrix.os }}
        path: bin/calc

  deploy:
    name: Deploy to S3
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write # For OIDC based authentication

    steps:
    - name: Download executable (x86_64)
      uses: actions/download-artifact@v4
      with:
        name: linux-executable-ubuntu-24.04
        path: x86_64-build/

    - name: Download executable (arm64)
      uses: actions/download-artifact@v4
      with:
        name: linux-executable-ubuntu-24.04-arm
        path: aarch64-build/

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ca-central-1

    - name: Upload to S3
      run: |
        aws s3 cp x86_64-build/* s3://rcbilson-dist/Linux/x86_64/
        aws s3 cp aarch64-build/* s3://rcbilson-dist/Linux/aarch64/
